name: av_control
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  firebase_core:
  firebase_auth:
  firebase_analytics:
  reactive_forms:
  material_design_icons_flutter:
  google_sign_in:
  sign_in_with_apple:
  crypto:
  google_fonts:
  flutter_native_splash:
  lottie:
  flutter_slider_drawer:
  flutter_carousel_widget:
  flutter_bloc:
  equatable:
  cloud_firestore:
  json_annotation:
  reactive_date_time_picker:
  date_format:
  intl: 
  cherry_toast:
  skeletonizer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
