// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBsHJem-cy8-4dRV6eVUIFC_qh8BbrmFQ',
    appId: '1:666082236827:web:b55f1e5931a68b7b5ce93e',
    messagingSenderId: '666082236827',
    projectId: 'av-control-b0aee',
    authDomain: 'av-control-b0aee.firebaseapp.com',
    storageBucket: 'av-control-b0aee.appspot.com',
    measurementId: 'G-RY5J1G8D3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTl-W2Vtu9CuJDE8bxORlbMx7bWWIy9Dg',
    appId: '1:666082236827:android:ec6ce1de44ffbdb05ce93e',
    messagingSenderId: '666082236827',
    projectId: 'av-control-b0aee',
    storageBucket: 'av-control-b0aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvxiA-JDSiqjb6WqHf3QYtlo0IG8_QJEs',
    appId: '1:666082236827:ios:f1427e0ac473f29d5ce93e',
    messagingSenderId: '666082236827',
    projectId: 'av-control-b0aee',
    storageBucket: 'av-control-b0aee.appspot.com',
    iosBundleId: 'com.example.avControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvxiA-JDSiqjb6WqHf3QYtlo0IG8_QJEs',
    appId: '1:666082236827:ios:0f92170d955104915ce93e',
    messagingSenderId: '666082236827',
    projectId: 'av-control-b0aee',
    storageBucket: 'av-control-b0aee.appspot.com',
    iosBundleId: 'com.example.avControl.RunnerTests',
  );
}
